### ISSUE TITLE
[FEAT.] : improve adding button and setting button

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#100]
**Is your feature request related to a problem? Please describe.**
I find that these buttons are a bit blotchy, and the add button is not very intuitive

**Comment by GaetanGrd** [comment]
@Zagrios  u don't close this issues ?

**Comment by Zagrios** [comment]
oups

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [improve adding button and setting button](https://trello.com/c/fVNxud8a/21-improve-adding-button-and-setting-button)
