### ISSUE TITLE
[BUG] : the icon is not correctly visible with the white themes of github and e BSM

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#123]
| Before | x | After | x |
| --- | --- | --- | --- |
|White|Black|white|black|
|![image](https://user-images.githubusercontent.com/40648115/214241771-b5085e9b-0c97-4571-94e6-f026aa5ee568.png)|![image](https://user-images.githubusercontent.com/40648115/214242136-dc181ef6-434b-49e1-8761-feb7d106b8c9.png)|![image](https://user-images.githubusercontent.com/40648115/214241833-0bdaf041-ad3a-4836-b8e9-bf9039684668.png)|![image](https://user-images.githubusercontent.com/40648115/214242083-eb150b30-0399-464f-a7f3-c6610ec2f347.png)|

Think Update :
- BSM
- Website
- Readme
- Nexus
- Discord
- other?

**Comment by Zagrios** [comment]
done in bsm here #125

**Comment by GaetanGrd** [comment]
don't close this issues ?
