### ISSUE TITLE
[BUG] : Header of Maps tab not translated

### ISSUE THREAD

**Issue by legoandmars** [Zagrios/bs-manager#150]
**Describe the bug**
When on an english install, "Maps partagées" will appear as a header at the top of the Maps tab

**To Reproduce**
1. Install bs-manager on Windows 11
2. Don't add/install any versions besides the current installation (1.27.0 on my setup)
3. Click the Maps tab on the left

(Likely reproducible without these instructions)

**Expected behavior**
Should be auto-translated using the `jsons/translations/...` feature

**Screenshots**
![image](https://user-images.githubusercontent.com/34404266/222009112-fd50a3b6-070b-42d5-b5ac-233be2b63dd0.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Version 22H2

**Comment by Zagrios** [comment]
Thanks! I will correct this quickly
