### ISSUE TITLE
[FEAT.] : Choose which folders are synced between versions similarly to custom songs

### ISSUE THREAD

**Issue by Morgolf** [Zagrios/bs-manager#155]
**Describe the solution you'd like**
For people that have multiple game versions, it would be nice to let us choose which folders are shared across different instalations, like custom songs are right now. This would allow us to have the same custom sabers, playlists, custom avatars etc. Let us choose which folders we want, trust us we know what we are doing :)

**Comment by Zagrios** [comment]
Hi, I work on a Model management system for BSManager (Like the Maps system but for Models) (currently paused) and u will be able to share your Models accross all your versions like Maps 😉

**Comment by Morgolf** [comment]
Will we be able to choose which folders we want to have shared manually? I for example have quite a few that I want to have shared, I use BS Legacy Launcher as of now and after seeing your app I was looking to switch but that is a functionality I need. My current linked folders list is:
CustomEnergyBars
CustomLevels
CustomMenuSongs
CustomNotes
CustomPlatforms
CustomSabers
CustomSongs
CustomSubRain
CustomWalls
CustomWIPLevels
DLC
NalulunaAvatars
Playlists

**Comment by Zagrios** [comment]
Hi, I was doing a small corrective update first, and now I'm moving on to this. We will be able to share all the folders that we want 😉
