### ISSUE TITLE
[BUG] : When loading maps, switching versions cause UI collision

### ISSUE THREAD

**Issue by AltyFox** [Zagrios/bs-manager#157]
When loading a maps folder for the first time, and you switch versions, it starts another scan, and the % indicator in the middle of the screen starts fighting between the two scanning threads causing jumps.
eg.
10%
45%
15%
50%

**Comment by GaetanGrd** [comment]
hey, next time, don't forget to use the templates, alright? 👀

**Comment by but2002** [comment]
Apologies!  I just hit the github page directly, didn't realize there was an auto build template! :)
