### ISSUE TITLE
[FEAT.] : Misleading description of "Oculus Mod" launch paramter

### ISSUE THREAD

**Issue by KnuckleDF** [Zagrios/bs-manager#162]
Problem: When selecting launch parameters, the "Oculus Mod" (mode?) button's info tab, which launches the game with the -vrmode oculus parameter, is worded in a way that implies it is required to be able to use any Oculus headset with the Steam version of the game. This is not the case, as Oculus headsets work fine with SteamVR games without any launch parameters.

Solution: Change the wording to something closer to "If you are running Beat Saber through Steam, this allows you to play the game as though it were the native Oculus version, bypassing SteamVR. This is not required to use Oculus headsets."

![image](https://user-images.githubusercontent.com/8597669/222280152-9fb996fe-5155-41eb-ae4b-a3ca0594eaf0.png)

**Comment by but2002** [comment]
A better phrase would be "Play in Oculus mode which can improve performance when using an Oculus headset"
Note:  I say "can" as in my experience on my Q2 with Oculus Link, I actually get better performance *without* using Oculus mode.

**Comment by Zagrios** [comment]
Oh i see thanks, i will change that
