### ISSUE TITLE
[FEAT.] : Steam login via OAuth

### ISSUE THREAD

**Issue by but2002** [Zagrios/bs-manager#163]
**Describe the solution you'd like**
Use OAuth for login instead of supplying your Steam user/pass

**Additional context**
People have issues with supplying apps with their direct password, for obvious reasons.   If possible, OAuth should be used to alleviate concerns.

**Comment by Iluhadesu** [comment]
It's not possible to download a game using an **OAuth token**, we already checked that (And it makes perfect sense). However we found a possible solution using **Steam's console**, and we will implement it soon.
