### ISSUE TITLE
[BUG] : UI elements overlap color selection panel in settings

### ISSUE THREAD

**Issue by Electrostats** [Zagrios/bs-manager#174]
**Describe the bug**

**To Reproduce**
1. Go to 'Settings'
2. Click on either one of the 'Appearance' Color 
3. Use the mouse wheel to scroll down

**Expected behavior**
The UI elements will overlap the color selection panel in settings 

**Desktop:**
 - OS: Windows 10 Pro Build 19045.2604 Version 22H2
 - Version v1.0.4

![Capture](https://user-images.githubusercontent.com/14132142/223269994-41eee68b-8f55-4711-ba13-65eb0e55938e.PNG)

**Comment by Zagrios** [comment]
fixed here 👌 #175
