### ISSUE TITLE
[FEAT.] : lunch steam from BSM

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#20]
When the notification "Steam is not running" appears, add the posibility to lunch steam.

Via [Steam browser protocol](https://developer.valvesoftware.com/wiki/Steam_browser_protocol)

`steam://open/games`

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [lunch steam from BSM](https://trello.com/c/aPNKUgWD/19-lunch-steam-from-bsm)
