### ISSUE TITLE
[FEAT.] : Option to auto-select a version on launch.

### ISSUE THREAD

**Issue by ChromiaCat** [Zagrios/bs-manager#200]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
AN option for BS Manager to auto-select the last version I had selected in it.
E.g. I got v1.28 and v.1.26 installed in BS Manager, I want to be able to set v1.26 for auto-select every time I start BS Manager.

**Comment by Morgolf** [comment]
This could be further improved if it allowed to create a shortcut to a specific version of the game that would allow to launch the game without launghing BSmanager. Either a shortcut or a launch option for BSmanager to instantly launch the last selected version of the game would be a big QOL improvement

**Comment by Zagrios** [comment]
For the shortcut its planned and it will propably be available for the next release ;)
