### ISSUE TITLE
[BUG] : steam guard code not trimmed

### ISSUE THREAD

**Issue by RobertasJ** [Zagrios/bs-manager#205]
**Describe the bug**

**To Reproduce**
1. try to install a version
2. when asked for steam guard code put it in with a trailing space.
3. get an error.

**Expected behavior**
.trim() gets called on the guard code.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 11
 - Version idk

**Additional context**

**Comment by Zagrios** [comment]
Thanks ! I will simply remove all spaces from the guard code.
This will be corrected in the next update 👍
