### ISSUE TITLE
[BUG] : Linking SongLevel folder

### ISSUE THREAD

**Issue by Naephilim** [Zagrios/bs-manager#224]
I found a problem with how the program links CustomLevels. When the installed instance is on a hard drive with not enough space for the songs and you have it linked, any song unable to fit on the hard drive just disappears. The program makes the original song folder as a shortcut, not the other way around, putting the real contents with the instance folder.

**Comment by GaetanGrd** [comment]
Thank you for your comment, @Naephilim .

We've taken note of your suggestion and are considering adding a notification to alert users when storage space is running low.

**Comment by Zagrios** [comment]
Fixed in [v1.5.0-alpha.4](https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.4)
