### ISSUE TITLE
[FEAT.] : Linux AppImage Support

### ISSUE THREAD

**Issue by Parapass** [Zagrios/bs-manager#226]
**Is your feature request related to a problem? Please describe.**

There is no AppImage available to use BSManager on Linux natively

**Describe the solution you'd like**

Use the publish script to also build an AppImage along with the Windows executables. 

**Describe alternatives you've considered**

Runs under Wine fine but requires .NET 6 which cannot be easily downloaded on Linux

**Additional context**

AppImages work across multiple different Linux distros

**Comment by RedlineTriad** [comment]
Working on linux support myself, the app image seems to have some extra issues though.
It doesn't have file permissions to write to anything (might be my problem idk) and also throws quite a few exceptions read only filesystem.
