### ISSUE TITLE
[BUG] : Can not use a network drive?

### ISSUE THREAD

**Issue by AndyIsHereBoi** [Zagrios/bs-manager#227]
**Describe the bug**

**To Reproduce**
Attempt to change install location to a network drive

**Expected behavior**
Should move all files there

**Screenshots**
![image](https://github.com/Zagrios/bs-manager/assets/69745145/5aabe965-0571-4345-96f5-ae924d3a7312)
![image](https://github.com/Zagrios/bs-manager/assets/69745145/63d81cae-2dbe-4f16-a82b-8874553033ee)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version v1.1.1

**Additional context**
Instantly fails to transfer files when i try to change it

**Comment by AndyIsHereBoi** [comment]
Did a little testing and it looks like when i run BSManager as admin it is still unable, but this time the windows explorer says this: 
![image](https://github.com/Zagrios/bs-manager/assets/69745145/09a0611e-495b-4f9e-b4d8-dadd48d4dcc6)

Not sure is this is a windows limitation as only my user is able to find it? or what but it does not work when trying to select it anymore.

**Comment by AndyIsHereBoi** [comment]
https://github.com/Zagrios/bs-manager/assets/69745145/573e6cca-3899-42f0-a712-0dc6e31b8112

**Comment by Zagrios** [comment]
Hey, thank you for all the details 😄 
Could you provide us with your log file?
Please ensure that the error is present in the log by attempting the action one more time before sending it. 
You can access the logs via 'Settings -> Scroll down -> Open Logs'.

**Comment by Zagrios** [comment]
It may take a bit longer to fix that issue because none of us have a network drive, but we are working on it 👌

**Comment by Tsaukpaetra** [comment]
Technically you can fake a network drive by going to `\\YOURCOMPUTERNAME\C$`  replacing your computer name and the drive letter.

**Comment by AndyIsHereBoi** [comment]
Any update on this? Still cannot use my network drive to store the files

**Comment by AndyIsHereBoi** [comment]
[2024-3-14-v1.4.7.log](https://github.com/Zagrios/bs-manager/files/14608390/2024-3-14-v1.4.7.log)
New logs though

**Comment by Zagrios** [comment]
@AndyIsHereBoi try to unlink all the folder that are curently linked (like the maps of the version 1.29.1) before moving your contents, the drive you'r trying to move your contents on may not support symlinks.
Can you tell me what file system is used by your network drive ?

**Comment by AndyIsHereBoi** [comment]
>Can you tell me what file system is used by your network drive ?

it is the default truenas filesystem, i picked samba for everything else

**Comment by AndyIsHereBoi** [comment]
Seems to work without the links. Doesnt look like they are supported on
samba

**Comment by Zagrios** [comment]
Oh okay, good to know 👌
Can I close the issue then ? @AndyIsHereBoi

**Comment by AndyIsHereBoi** [comment]
Yes
