### ISSUE TITLE
[BUG] : i cant click the play button while trying to play a song on a down graded version of beat saber on bs manager

### ISSUE THREAD

**Issue by Martycombarty** [Zagrios/bs-manager#228]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Iluhadesu** [comment]
Hello,
Your issue isn't related to BSManager, it's probably an issue with the mods you installed or the version of beat saber you used. I suggest you to install a more recent version (e.g 1.29.1 which is the lastest moddable version) or join the [BSMG's discord](https://discord.gg/beatsabermods) in the "pc-help" channel and describe your problem there.
