### ISSUE TITLE
[FEAT.] : be able to name different version's added

### ISSUE THREAD

**Issue by camdenbrandt** [Zagrios/bs-manager#230]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Zagrios** [comment]
Hi, i'm not sure i totally understand what you want, but if you want to rename your version its already possible by clicking on the gear icon on your version page (at top right) then "Edit" 😉

**Comment by Zagrios** [comment]
close due to inactivity
