### ISSUE TITLE
[FEAT.] : 

### ISSUE THREAD

**Issue by NineLivez189** [Zagrios/bs-manager#234]
add the feature to be able to auto import settings and maps from steams version of the game to the down graded version i had to manually copy and paste all of my songs from steam to the down graded version

**Comment by Zagrios** [comment]
Hi, you can already do that by linking your Maps of your Steam version and your maps of your downgraded version.
By doing that, your maps will be synced between those versions.

(see gif)
![link maps](https://github.com/Zagrios/bs-manager/assets/40181755/fa1eae06-dc7c-4aae-b631-9cb1a42f4ff2)

For your settings you can also link the folder "UserData" between the versions.
(see gif)
![userdata](https://github.com/Zagrios/bs-manager/assets/40181755/cf4a46d6-04c6-4adf-b3f9-9b2ad240cb3b)
