### ISSUE TITLE
[FEAT.] : ArcViewer preview

### ISSUE THREAD

**Issue by ibillingsley** [Zagrios/bs-manager#237]
**Is your feature request related to a problem? Please describe.**
Current map preview does not support V3 maps (arcs & chains), and has to redownload local maps to preview them.

**Describe the solution you'd like**
[ArcViewer](https://github.com/AllPoland/ArcViewer) supports V3 maps. It has both a [web version](https://allpoland.github.io/ArcViewer/) and [desktop version](https://github.com/AllPoland/ArcViewer/releases).

BSManager could use the web version by default, with an option to provide a path to ArcViewer.exe to use the Desktop version. The advantage of the Desktop version is that local maps could be previewed without redownloading them.

**Additional context**
Documentation for URL and command line arguments: 
https://github.com/AllPoland/ArcViewer/wiki/URL-Argument-Docs

**Comment by Zagrios** [comment]
Hi, thanks for reminding us of that. We will use the ArcViewer in a next update 👌
