### ISSUE TITLE
[BUG] : Desktop shortcut shows incorrect message

### ISSUE THREAD

**Issue by supercrafter100** [Zagrios/bs-manager#239]
**Describe the bug**
When hovering over the desktop shortcut that was created during installation, it says "A foundation for scalable desktop apps" which I'm guessing is coming from the framework that was used to build the application in the first place. It's nothing major just a small visual bug I'm guessing.

**To Reproduce**
1. Install bs-manager, making sure to create a desktop shortcut automatically
2. Hover with your mouse over the newly created shortcut of BSManager

**Expected behavior**
Show a relevant message or none at all

**Screenshots**
![image](https://github.com/Zagrios/bs-manager/assets/58982133/7f9daa6d-cb4e-4b3e-b782-eda3c6022e52)

**Desktop (please complete the following information):**
 - OS: [Windows 11 Pro]
 - Version [10.0.22624 Build 22624]

**Additional context**
None

**Comment by Zagrios** [comment]
Wow thank you for telling us that, we will correct quickly 👌
