### ISSUE TITLE
[FEAT.] : CI for automated builds, test, linting, code quality, and coverage.

### ISSUE THREAD

**Issue by RedlineTriad** [Zagrios/bs-manager#265]
**Is your feature request related to a problem? Please describe.**
Currently it's easy for PRs to break builds, and introduce bad formatting.
This means more working during reviews, and also accidental diffs in other PRs if there is non standard formatting.

**Describe the solution you'd like**
I think it would be good to have this automated for PR's and main branch with GitHub Actions
- [x] Builds
- [x] Tests
- [x] Linting
- [x] Sonarcloud code quality
- [ ] Sonarcloud test coverage

**Describe alternatives you've considered**
Instead of Sonarcloud we could also use Codacy, or Code Climate, though I have less experience with it.

**Additional context**
Automated deployment would also be nice, but this is a relatively easy to implement start.
Also, I would be willing to implement this myself, though I might need permissions or someone else to do it for sonar.

**Comment by RedlineTriad** [comment]
Mostly creating this issue to figure out if this would even be wanted or if I would be wasting my time by creating PR's.
@Zagrios So if you could tell me if you were open to some automation please give me the go-ahead :D

**Comment by Zagrios** [comment]
Yeah go ahead 😉 🚀

**Comment by Zagrios** [comment]
I've added SonarCloud GitHub action for code quality, but idk if it include test coverage tho 🤔

**Comment by RedlineTriad** [comment]
I can try and add test coverage in a separate pr, not always easy especially with multiple platforms.

**Comment by Zagrios** [comment]
As we talked here https://github.com/Zagrios/bs-manager/commit/b3251595ab167d2fc0ee07357739fff0fa938bfe#commitcomment-120406253, I think we can drop code coverage for now and keep workflows for Build, Lint, And SonarCloud auto analysis
