### ISSUE TITLE
[FEAT.] : Moving the configuration file

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#27]
We need to move the location of the user configuration file.

This file must be moved to the BSManager folder, so the user can copy the BSManager data folder without losing its configurations, versions, etc.

To do this, it's in the `configuration.service.ts`. You need to passe the option {cwd: [BSMFolder]} to ElectronStore contructor.

But you will still need to keep saving the BSM data path in the AppData folder.

https://www.npmjs.com/package/electron-store?activeTab=readme

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Moving the configuration file](https://trello.com/c/rkO2s8fa/38-moving-the-configuration-file)
