### ISSUE TITLE
[FEAT.] : Add a support for oculus pcvr

### ISSUE THREAD

**Issue by lorke1** [Zagrios/bs-manager#274]
I would like a pcvr version for the oculus buyers.
I have bought the oculus version of pcvr which is from oculus but it is on the computer.

**Comment by Zagrios** [comment]
Yep this is feature that we've already planned, it will come in the near future 😉

**Comment by lorke1** [comment]
Hey thanks for answering nice to hear that. 😇
I know what I am going to say isn't polite and I will understand if you won't answer, do you have any idea when it will be released by you and your team?
P.S don't want to pressure do it at your own speed. 🙃

**Comment by Zagrios** [comment]
Hi, we're hoping to release support for Oculus PC before september, but as always, timelines can shift based on various factors 😉

**Comment by lorke1** [comment]
Hi, I was wondering when is it going to be released today.
I really want to use the version feature and try new updates while i can keep my older versions.
Is there a new date?
Thanks! 😅

**Comment by Zagrios** [comment]
Unfortunately, this feature will not be available very soon. Indeed, we are working on it, but we are all very busy at the moment :/
