### ISSUE TITLE
[BUG] : Crashing when loading Maps

### ISSUE THREAD

**Issue by wmmc88** [Zagrios/bs-manager#276]
**Describe the bug**
I recently copied over my large map library to the shared maps folder. Now, BSManager crashes whenever I try to look at maps. It loads to around 40% then crashes to desktop.

**To Reproduce**

1. Open BSManager
2. Click Shared
3. Maps load until ~30-40%
4. Crash

**Expected behavior**
No Crash

**Desktop (please complete the following information):**

-   OS: W11
-   Version Build 23493

**Additional context**
Logs: [2023-7-4-v1.2.0.log](https://github.com/Zagrios/bs-manager/files/11951667/2023-7-4-v1.2.0.log)

**Comment by Zagrios** [comment]
Hi, for a rough estimate, can you tell me how many maps you have?

**Comment by wmmc88** [comment]
I used to sync a lot of playlists via syncsaber so there's a lot. Just over 9000 right now.
