### ISSUE TITLE
[BUG] : My beat saber wont stay open when running this

### ISSUE THREAD

**Issue by TavisFox** [Zagrios/bs-manager#280]
**Describe the bug**
Any time I try to open beat saber through the application to get my mods in the game, beat saber immediately just shuts down after like 5 seconds and either is no where to be found or becomes a background task on task manager but unviewable completely. In addition it will make me go through two "do you want to let steam makes changes to your device" prompts and no matter if I click yes or no on both it usually ends with my steam vr saying "critical error occurred quit or restart steam vr". I've tried restarting my pc, I've tried redownloading the game, deleting and redownloading files, I don't know what I'm doing wrong at this point. I know I keep having a "7xza.dll not found" when I try unzipping the .zip file that's linked as well so maybe that has something to do with it? but I cant even get that to work from what I've found online.

**Screenshots**
![image](https://github.com/Zagrios/bs-manager/assets/131593311/a70cffb1-bef1-4037-bf80-04a2bb81d9e1) 
![image](https://github.com/Zagrios/bs-manager/assets/131593311/ba1b13ec-1df5-42db-93cc-5597450c3047)

**Desktop (please complete the following information):**

-   OS: [Windows]
-   Version [10]

**Additional context**

**Comment by Zagrios** [comment]
Hi, thank you for reporting this issue. I recommend that you join our Discord and open a thread in the "Support" channel. There are more people who can assist you, and we will be able to help you more quickly 😉 

https://discord.gg/uSqbHVpKdV

**Comment by Zagrios** [comment]
I see its resolved on Discord, so I close 👌

**Comment by Bielecki** [comment]
What's the solution? There are issues so everyone can see what was wrong and what's the solution. It's not resolved, when issue still persist - like in my case.
