### ISSUE TITLE
[FEAT.] : Make notifications swipeable

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#29]
**Describe the solution you'd like**
Just swipe on the right to close the notification.

we can use :
https://github.com/hammerjs/hammer.js

or maybe framer-motion

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make notifications swipeable](https://trello.com/c/XXKPwqWH/37-make-notifications-swipeable)
