### ISSUE TITLE
[FEAT.] : Pause and resume Download

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#30]
Hey, can u add possibility to pause and resume download ?

**Comment by Zagrios** [comment]
Hi, which download are you talking about?

**Comment by GaetanGrd** [comment]
The download of beat saber versions

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pause and resume Download](https://trello.com/c/Uejw9j0V/14-pause-and-resume-download)

**Comment by GaetanGrd** [comment]
this feature is not implemented in depoDownloader so i close this issue
