### ISSUE TITLE
[BUG] : PrioritySetter and GottaGoFast never show as installed

### ISSUE THREAD

**Issue by Insprill** [Zagrios/bs-manager#302]
## Bug Description
When attempting to install PrioritySetter or GottaGoFast, they get unchecked from the GUI after installation is finished, even though they are installed in the game.

## Reproduction Steps
- Download Beat Saber 1.31.0 (possibly an issue on other versions)
- Go to the Mods tab, and try to install `PrioritySetter` or `GottaGoFast`.
- Observe they both get unchecked after the installation process is complete.
- Observe the actual mods being installed in the game's plugins directory.

## Expected Behavior
The mods should be able to be installed, or if they can't be installed for some reason, and notification should be shown to the user.

## System Specs
- OS: Windows 10
- BS Manager Version: v1.3.0

**Comment by Zagrios** [comment]
After verifying, the issue lies with the BeatMods API, which has incorrect MD5 hashes for the DLLs corresponding to these two mods.
It will maybe be fixed after an update of the Mods in BeatMods
