### ISSUE TITLE
[FEAT.] : Map preview volume control slider

### ISSUE THREAD

**Issue by sacreddany** [Zagrios/bs-manager#315]
## Problem
 
 I hate it when the map preview sound is a bit loud and covers any other sound i.e. discord.

## Solution
 A slider in the menu would be great if not too much work
 Moving the slider lower or higher would likewise set the volume of the map preview sound to that % out of 100

**Comment by Iluhadesu** [comment]
It's already available look next to the window controls :)
![image](https://github.com/Zagrios/bs-manager/assets/92525749/30bc336a-aa4f-4dc5-b73f-25b0ee393fc7)

**Comment by Zagrios** [comment]
And if you're referring to the actual preview of the map, you have that: :
![image](https://github.com/Zagrios/bs-manager/assets/40181755/4ba5de45-153c-4d2a-8a47-a779c4ea3cc3)

**Comment by Zagrios** [comment]
Don't hesitate to reopen if it doesn't respond to what you meant 👌
