### ISSUE TITLE
[BUG] : whenever i try to open it, it just crashes, im on quest link for my quest 2, please help me

### ISSUE THREAD

**Issue by hello6542** [Zagrios/bs-manager#317]

**Comment by Zagrios** [comment]
You are on Quest Link right ? When you open BSM, does it instantly crash? Or are you doing something before the crash?

Also can you send the your BSM logs here ? (Settings -> scroll down -> "open logs")

**Comment by Zagrios** [comment]
Closed due to inactivity.
Don't hesitate to reopen if needed
