### ISSUE TITLE
[FEAT.] : When double click map = launch DL

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#33]
hey, it's possible to when double click on map, BSM launch de DL of this ?

**Comment by Zagrios** [comment]
Thanks ! Have been implemented on the developpment branch, will be present in the next release 👌
For traking : [5d62c6c](https://github.com/Zagrios/bs-manager/commit/5d62c6c0e9a614642fe814357c47b4367e40cd28)

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [When double click map = launch DL](https://trello.com/c/YBsRxJa1/34-when-double-click-map-launch-dl)
