### ISSUE TITLE
[BUG] : not running

### ISSUE THREAD

**Issue by RealFischi** [Zagrios/bs-manager#332]

**Comment by Zagrios** [comment]
Hi, what happened exactly ?

BSManager is simply not launching ?

If you have an error window can you send a screenshot here ?

Or can you send your logs here ? 
Logs are located here `C:\Users\{UserName}\AppData\Roaming\bs-manager\logs`

**Comment by Zagrios** [comment]
Closed due to inactivity.
Don't hesitate to reopen if needed
