### ISSUE TITLE
[FEAT.] : add visual effect to signal "already have map"

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#34]
hey, can you add a visual effect to say that we already have the map? 

Example : 
![image](https://user-images.githubusercontent.com/40648115/209417907-6e192ba4-8abe-4297-9483-ddc59a5af667.png)

**Comment by Zagrios** [comment]
The download button is already hidden when you have the map, you think is that not enough?

**Comment by GaetanGrd** [comment]
Pour télécharger quelque Map ce n'est pas dérangeant mais c'est agréable quand on eût juste DL plein de Map sans vraiment regardé, c'est frustrant d'être coupé dans son élan car tu rate un clic

**Comment by GaetanGrd** [comment]
Not really, we quickly get lost on what is downloaded and what is not

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add visual effect to signal "already have map"](https://trello.com/c/yvd9cOCH/33-add-visual-effect-to-signal-already-have-map)
