### ISSUE TITLE
[BUG] : Earlier BeatSaber versions immediately crashing upon launch.

### ISSUE THREAD

**Issue by Chenghiskhan** [Zagrios/bs-manager#343]
## Bug Description
After downloading version 1.28.0 from the "add a version" feature of BSManager, attempting to launch the older version causes Beatsaber to load for a second before immediately closing.

## Reproduction Steps
1. Click on **+ -> Add a version** at the bottom left of BSManager.
2. Select 1.28.0 and click on **Download**.
3. After 1.28.0 downloads, select it from the left-hand bar and then click on Launch (any mix and match of the three launch options yields the same results, I have FPFC and Debug ticked for the log attached).

## Expected Behavior
Expected that BeatSaber 1.28.0 launches. At the moment of writing, 1.33.0 is the current version and launching that through BSManager is instant and flawless.

## Screenshots
n/a

## System Specs
Desktop
OS: Windows 10
CPU: Ryzen 5600X
GPU: EVGA FTW 3080
RAM: 32 GB 3600 MHz DDR4

## Additional context
See attached report for crash log.
[2023-10-31-v1.3.2.log](https://github.com/Zagrios/bs-manager/files/13222777/2023-10-31-v1.3.2.log)

**Comment by Chenghiskhan** [comment]
As an update, the farthest version I can roll back to seems to be 1.31.1, which launches successfully.

**Comment by Zagrios** [comment]
Hi, thanks all the details! But when BS crashes, BSManager probably isn't in cause. I'd suggest you post your issue in the BSMG Discord, under the #pc-help channel 😉
https://discord.gg/beatsabermods

**Comment by Zagrios** [comment]
Assume the issue is resolved.
Don't hesitate to reopen if needed
