### ISSUE TITLE
[BUG] : BSManager instantly deleted install when i verified files

### ISSUE THREAD

**Issue by un-simp** [Zagrios/bs-manager#344]
## Bug Description
when i was trying to access my game files i accidentally clicked on verify files and i couldn't cancel it then my install deleted

## Reproduction Steps

choose install
select verify files
observe

## Expected Behavior
it would verify first 

## System Specs

OS Windows 10 LTSC Iot

**Comment by Zagrios** [comment]
Hi, sorry response time
Are you still able to reproduce this issue ?
If yes can you send your latest log file here ?
(settings -> scroll down -> click on "open logs")

**Comment by un-simp** [comment]
hi, i was unable to reproduce it but i know that a couple other people have been having this issue with their custom songs when linking

**Comment by Zagrios** [comment]
The issue with linking is fixed in the [v1.5.0-alpha.4](https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.4)
