### ISSUE TITLE
[FEAT.] : Setting to open on verison instead of homepage

### ISSUE THREAD

**Issue by Ai-Kiwi** [Zagrios/bs-manager#350]
## Problem
I'm always frustrated when I have to make an extra click to click on the version. Huge waste of time! I lose a whole 2 seconds from my day, Maybe even 3!

## Solution
Have a setting so when the app starts it auto opens to a version so it is one click away from you start it. 

## Alternative solutions (if any)
Could have a way where you can add start parameters to open a version on start. That way you could add quick links to your desktop.
Not really an alternative but another cool idea would be it detects when you load into vr and then automatically starts a version of beat saber you set. Not sure how this would work but could be cool!

**Comment by Zagrios** [comment]
Hi, you can already create shortcuts to launch versions  without openning BSM

![image](https://github.com/Zagrios/bs-manager/assets/40181755/d408e640-6976-40ea-ba21-53fe60e2b3a5)

**Comment by Ai-Kiwi** [comment]
> Hi, you can already create shortcuts to launch versions  without openning BSM
> 
> ![image](https://github.com/Zagrios/bs-manager/assets/40181755/d408e640-6976-40ea-ba21-53fe60e2b3a5)
> 

Ah, I'm smart. Thank you for the reply this has fixed my problem.

**Comment by Zagrios** [comment]
😉
