### ISSUE TITLE
[FEAT.] : Add "reset" button for custom name version

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#361]
a picture explains more than words... 

Is it possible to get this? 
![image](https://github.com/Zagrios/bs-manager/assets/40648115/6151e423-71ce-4c2a-b1f0-6b226a82607b)

instead of this
![image](https://github.com/Zagrios/bs-manager/assets/40648115/ac4456e4-52c3-44fb-b377-1f73d2fff4b0)

**Comment by silentrald** [comment]
@Zagrios can close this issue, the linked PR should have solved this issue.
