### ISSUE TITLE
[BUG] : there is no game version to lunch even after installing them...

### ISSUE THREAD

**Issue by HannibalP** [Zagrios/bs-manager#380]

**Comment by Zagrios** [comment]
Hi, can you send your logs here ?
Go to setting -> scroll down -> click on "open logs"

**Comment by HannibalP** [comment]
Sorry I found the problem. It was windows11 that blocked the accès of the
files from BSManager after the update...

Le jeu. 21 déc. 2023 à 22:22, MathieuG-P ***@***.***> a
écrit :

**Comment by Zagrios** [comment]
Happy to ear that 🙌 
Enjoy Beat Saber 💪
