### ISSUE TITLE
[BUG] : 1.29.1 Version Crashing

### ISSUE THREAD

**Issue by BOTAIBSABER** [Zagrios/bs-manager#382]
## Bug Description
 BeatSaber crashing whenever I try to launch the 1.29.1 version from BSmanager. 1.29.1 is the only version that has this bug for me.

## Expected Behavior
I expected BeatSaber to open but instead it instantly crashes.

**Comment by Zagrios** [comment]
This is most likely not related to BSManager.
You may find better help on BSMG discord : https://discord.gg/beatsabermods
(Don't hesitate to reopen this issue if needed)
