### ISSUE TITLE
[BUG] : A problem with launching the game.

### ISSUE THREAD

**Issue by idjqhs** [Zagrios/bs-manager#387]
## Bug Description
 I am not sure if it is a bug but when I want to play modded beat saber with my oculus ready my pc ready both being connected then I click launch nothing happens and need to go to steam to launch beat saber but from there it automatically launches the newest version which doesn't have as many things available.

## Expected Behavior
 My expectation was that bs manager would launch the game straight from bs manager itself.

**Comment by Zagrios** [comment]
Hi, can you send your logs ?
(Go to settings -> scroll down -> "open logs")

**Comment by idjqhs** [comment]
Sorry that I didn't reply quicker. I just didn't really care about this and now OST 7 brought me back but anyways what am I supposed to do? Screenshot the folder?
