### ISSUE TITLE
[BUG] : I am unable to use my meta access token in BSManager

### ISSUE THREAD

**Issue by AtxmOM** [Zagrios/bs-manager#393]

**Comment by AtxmOM** [comment]
![image](https://github.com/Zagrios/bs-manager/assets/155592130/d33da794-757c-4ca8-8b7e-b4cfbe7970f9)

**Comment by Zagrios** [comment]
Hello, please ensure that you have well followed this guide: https://github.com/Zagrios/bs-manager/wiki/How-to-obtain-your-Oculus-Token

If the issue persists, verify that you possess Beat Saber for Oculus Desktop. Owning the game on Quest standalone does not imply you own the Desktop version; they are two separate things.

Keep me posted 😉
