### ISSUE TITLE
[BUG] : BSModmanager game not launching

### ISSUE THREAD

**Issue by ItzWolfi** [Zagrios/bs-manager#394]
## Bug Description
When i try to start a Beat Saber version for example 1.29.1 with my Meta Quest 2 through steam vr it opens the game but it's just a black screen and i can't do anything.

## Reproduction Steps

1. Open ModManager
2. Select a version
3. Click launch
4. Game is on a black screen

**Comment by Zagrios** [comment]
Hi make sure the FPFC mode is not enabled.
If you still have the issue this is most likly not related to BSManager. You may find better help asking on BSMG Discord under the #pc-help channel\
https://discord.gg/beatsabermods
