### ISSUE TITLE
[BUG] : Can't open the game with BS manager 

### ISSUE THREAD

**Issue by GeorgeMixas** [Zagrios/bs-manager#395]
## Bug Description
When I try to open the game through BS manager it doesn't open, it either gives me a black screen or Beat Saber doesn't open at all, I have been using BS manager for months and this is the first time something like that has happened, two days ago it was working fine and I didn't change anything since then, Tried opening an unmodded version of the game as well and it again didn't work, opening the game through steam works fine.

## Reproduction Steps
1. Select a version and click play

## Expected Behavior
for the game to open normaly.

## System Specs
i7-4790k
GTX 1080
16 GB ddr3 ram
MB maximus vi hero

## OS
- Windows 10 Version 10.0.19045 Build 19045

## Manager log
[2024-1-4-v1.4.3.log](https://github.com/Zagrios/bs-manager/files/13835726/2024-1-4-v1.4.3.log)

## Game log
[_latest.log](https://github.com/Zagrios/bs-manager/files/13835738/_latest.log)

**Comment by Zagrios** [comment]
Hi,
I see the version you launching is an Oculus version is that normal ?

**Comment by GeorgeMixas** [comment]
Hello, what do you mean that it's a version downgraded from Oculus? 

I'm trying to open 1.29.1 Steam version of the game in Oculus mode but without having an Oculus headset.

**Comment by Zagrios** [comment]
Oh yeah sorry I read the wrong line in the logs mb 😅
Yea the admin issue its a know issue that we must and should be fix in the next release

(I let this issue open for now, i will close it when the admin issue is fixed in BSM)
