### ISSUE TITLE
[FEAT.] : Hitboxes

### ISSUE THREAD

**Issue by justplayingog** [Zagrios/bs-manager#396]
## Problem
Hitboxes
are so fcking bad that i can't really play any of the maps while playing on bsmanager.

## Solution
Adding hitboxes menu.
It would help alot of players when you would add an hitboxes changing menu.

## Additional context
Bro all i want to do is play the beat saber with mods, but i can't cuz of those hitboxes. At least try doing an ,,hitbox training mode"

**Comment by Zagrios** [comment]
That's not BSManager related, ask on BSMG discord for help 
https://discord.gg/beatsabermods
