### ISSUE TITLE
whenever I attempt to open Beat saber from Bs manager it always closes instantly [BUG] :       

### ISSUE THREAD

**Issue by Rolandelving** [Zagrios/bs-manager#401]
## Bug Description
So when I first open Bs manager everything is fine but then when I try to open beat saber from BS manager it instantly closes but if I go and open it from steam it opens completely fine but with no mods because bs manager has the modded version and I tried uninstalling then reinstalling and also new drivers etc.

## System Specs
core !7 10400k 
3060 graphics card
16gs RAM
1TB SSD
fan-cooling

-   OS: Windows 11
-   Version 1.29.1

**Comment by Zagrios** [comment]
Hi, try to run BSManager as admin, this problem can occur if Steam is running as Admin and BSManager is not.

If you still have the issue, join our discord it will be easier to help you over there
