### ISSUE TITLE
[BUG] : Beat Saber - I moved files and now it acts weird, I've moved them back now its still not the same

### ISSUE THREAD

**Issue by Panda11177** [Zagrios/bs-manager#402]

**Comment by Panda11177** [comment]
I need help

**Comment by Zagrios** [comment]
If its an issue directly inside the game, is most likely not related to BSM
Try to ask in BSMG discord, in the #pc-help channel
https://discord.gg/beatsabermods

**Comment by Zagrios** [comment]
Don't hesitate to re-open if needed
