### ISSUE TITLE
[BUG] : Unable to uninstall old versions of Beat Saber

### ISSUE THREAD

**Issue by omgitsraven** [Zagrios/bs-manager#424]
## Bug Description
When I select 'uninstall' from the gear menu on an older version of Beat Saber in BSManager, nothing happens (no error, but also the old version remains installed).

## Reproduction Steps
1. Click the old version in the list on the left
2. Click the gear in the top right
3. Click 'Uninstall' in the menu
4. Click 'Uninstall' on the popup that appears
5. BSManager now selects the latest version installed, but, the old version is still present in the list, even after relaunching.

## Expected Behavior
That version would be removed from the list.

## System Specs
-   OS: Windows 10
-   Version 10.0.19045

## Additional context
It's possibly relevant that when I select 'edit' and type in a new name, a message pops up that says 'renaming impossible'.

**Comment by omgitsraven** [comment]
BTW, rebooting just resolved this for me, so, it's not exactly urgent.   still worth knowing though imo

**Comment by Zagrios** [comment]
Reopen if needed
