### ISSUE TITLE
“Error Loading Data” DLC after mods?

### ISSUE THREAD

**Issue by kyrstannie** [Zagrios/bs-manager#427]
Hi, I apologize if this has been asked before, but I’m running into some DLC access issues when I use BS Manager to install 1.29.1 for mod support. Mods work, but all of my DLC from Steam only works in the latest 1.34.6 Steam version. When I try to play the DLC in 1.29.1 or any other version, it just says “Error Loading Data.” Is there a way I can get the DLC to work for these mod supported versions of Beat Saber? Would love some help, thank you!

**Comment by LazerSkar** [comment]
depending with some dlc, but you need to go into the files and yoink the dlc map and put it into the 1.29 version's DLC folder... thats the only way ive been able to do it :|

**Comment by kyrstannie** [comment]
> depending with some dlc, but you need to go into the files and yoink the dlc map and put it into the 1.29 version's DLC folder... thats the only way ive been able to do it :|

Thank you so much for helping me. Can you show me how (screenshot maybe)? Because I put 1.34.6 Steam version's DLC folder into the 1.29 version's DLC folder but didn't work =(

**Comment by Zagrios** [comment]
Hi @kyrstannie sry response time 😅 
BSManager doesn't have the ability to download DLCs for your downgraded versions yet
I beleave you may have to use external tools for that, BSMG discord can help you with that (in the #pc-help channel)
https://discord.gg/beatsabermods

**Comment by LazerSkar** [comment]
![image](https://github.com/Zagrios/bs-manager/assets/107281931/9c7a9f0a-d391-4539-9108-6c80b10edccc)
![image](https://github.com/Zagrios/bs-manager/assets/107281931/a659fb20-706e-4e43-9e91-7b57910d047e)

here is an example. my right folder is my 1.29, the left is my 1.32 modded and i put my game on 1.32.2 at the time on steam, got the dlc, then copied it into my modded 1.32 folder, now my dlc work on it

**Comment by LazerSkar** [comment]
also dont ask about my oined onedrive files :|

**Comment by LazerSkar** [comment]
> > depending with some dlc, but you need to go into the files and yoink the dlc map and put it into the 1.29 version's DLC folder... thats the only way ive been able to do it :|
> 
> Thank you so much for helping me. Can you show me how (screenshot maybe)? Because I put 1.34.6 Steam version's DLC folder into the 1.29 version's DLC folder but didn't work =(

it depends with the DLC map version.  if that song had been remaped or v3 lighting, it wont work... but of my case the song (already over) was made for later versions of beat saber, so i got my hand on the dlc from downloading a non modded version of the latest version of beat saber, here is my example from my steam version of the game i updated, grabbed the song and put it in the DLC folder, it worked for me as shown on the right, the song shows up, the map works and i can play through it
![image](https://github.com/Zagrios/bs-manager/assets/107281931/ab7c4706-7435-498b-9617-08b293bb5ce3)

**Comment by LazerSkar** [comment]
i had this problem i just though maube a copy paste fixes it... and it does under the right circumstances

**Comment by kyrstannie** [comment]
@Zagrios @LazerSkar ty you so much for helping me!
Now it is working here! 🥰💜

**Comment by LazerSkar** [comment]
sry for the longer reply before but no problem :)

**Comment by kyrstannie** [comment]
No problem at all! Your images and examples were really useful!
Thanks again! 😊
