### ISSUE TITLE
[BUG] : Game does not respond to any input

### ISSUE THREAD

**Issue by Justgamer03** [Zagrios/bs-manager#428]
## Bug Description
When I load up a modded version of the game, it starts the game but then gets stuck in the main menu and I cant interact with the game at all. All other functions, such as Steam VR still respond like normal.

## Reproduction Steps

Its an issue I have face before on my old computer but smh it fixed itself. However ever since ive got my new computer, its here again and I cant plan 1.29,1 with mods active

**Comment by Zagrios** [comment]
I believe that's a known issue but its not related to BSManager, ask on the BSMG discord in the #pc-help channel they will help you with this
https://discord.gg/beatsabermods

I close this issue, don't hesitate to reopen if needed.
