### ISSUE TITLE
[FEAT.] : Add discord button

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#43]
**Describe the solution you'd like**
Add discord button to join this server https://discord.gg/D4Jk3C2KeC

**Comment by GaetanGrd** [comment]
Don't forget update discord link in README 
https://github.com/Zagrios/bs-manager/tree/Readme-Update

**Comment by GaetanGrd** [comment]
Hi Zagrios, I realize that I have confused you with discord links, could you put this discord link? 
https://discord.gg/D4Jk3C2KeC

This will differentiate between people who join from the readme and those who join from the software.

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add discord button](https://trello.com/c/z5p4XlIO/32-add-discord-button)
