### ISSUE TITLE
[BUG] : Beat Saber 0.10.1 stuck on black screen upon launch

### ISSUE THREAD

**Issue by overlappingd** [Zagrios/bs-manager#430]
## Bug Description
Whenever I try to launch Beat Saber v0.10.1, it gets stuck on a black screen. I do not understand this as I launched it a few days ago and it was fine. I have installed the latest graphics drivers from NVIDIA and I don't know what else to do.

## Reproduction Steps

1. Install 0.10.1
2. Click on '0.10.1' in the sidebar menu
3. Click on 'Launch'

## Expected Behavior
Expected it to launch and work perfectly normally.

## Screenshots
![image_2024-03-03_193204335](https://github.com/Zagrios/bs-manager/assets/137969793/b1e25b7d-069d-4d27-bfd9-9a8e6ae8bd28)
Image of Beat Saber 0.10.1 blackscreening. Tha taskbar shows that Beat Saber **is** open.
![Screenshot 2024-03-03 192714](https://github.com/Zagrios/bs-manager/assets/137969793/84ec9f1f-adb9-4f2b-b887-341eb7a5b01e)
Image of NVIDIA Geforce Experience (where I download my drivers), and it saying my driver is up to date.

## System Specs
**Desktop (please complete the following information):**

-   OS: Windows
-   Version: 11 (Insider Build: 23620.ni_prerelease.240118-1056)

## Additional context
No other context.

**Comment by Zagrios** [comment]
This type of bug is most likely not related to BSManager
You will have better help asking on the BSMG discord under the #pc-help
https://discord.gg/beatsabermods

(don't hesitate to re-open if needed)
