### ISSUE TITLE
[FEAT.] : Add disclaimer modal before use mods

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#44]
**Is your feature request related to a problem? Please describe.**
Mods can sometimes break a version of Beat Saber. We need to add a readme modal that user must accept before use modding system.

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add disclaimer modal before use mods](https://trello.com/c/tAQcdyOA/31-add-disclaimer-modal-before-use-mods)
