### ISSUE TITLE
[BUG] : Game doesnt launch into VR

### ISSUE THREAD

**Issue by naminode** [Zagrios/bs-manager#446]
## Bug Description
Game launch only on desktop, not in VR

## Reproduction Steps
When launching downloaded version ( 1.34.2 , Steam Link)

## Expected Behavior
Game launch only into windows desktop, not into VR. FPFC is not turn on

## System Specs
-   OS: Windows 11
     i7 12700
     32 gb 3600
     RTX3080

**Comment by Zagrios** [comment]
Issue resolved in discord.

The solution was to set OpenXR as default runtime on Steam.

![image](https://github.com/Zagrios/bs-manager/assets/40181755/f698ad81-4252-41b7-9da0-ab8b70f81179)
