### ISSUE TITLE
[BUG] : Can not click play on any song in bs-manager

### ISSUE THREAD

**Issue by Johanoka** [Zagrios/bs-manager#448]
## Bug Description
Everything until I press play on a song functions fine but as soon I try to press "play" on any song nothing happens.

## Reproduction Steps

1. Go to 'Solo'
2. Click "play" on any song
3. Nothing happens
-->

## Expected Behavior
I expected it to play the song.

## System Specs
Windows 10
Steam

**Comment by GaetanGrd** [comment]
hey this problem is not related to BSManager, try asking on the BSMG discord server 
https://discord.gg/beatsabermods
