### ISSUE TITLE
[FEAT.] : Update Readme file

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#45]
update the readme file, to have a more complete presentation, 
also create a readme for Nexus Mods without markdown and image (text only)

**Comment by Zagrios** [comment]
`BSManager` not `Beat Saber Manager`

**Comment by GaetanGrd** [comment]
gngngngngn

**Comment by Zagrios** [comment]
`BSManager` not `BS Manager`
And just to not forget, first image in English please

**Comment by GaetanGrd** [comment]
éo ur repo named "bs-manager" gngngngn xD

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Readme file](https://trello.com/c/tXq0QrdX/30-update-readme-file)
