### ISSUE TITLE
[BUG] : im stuck on installing

### ISSUE THREAD

**Issue by EclipseWMods** [Zagrios/bs-manager#465]

**Comment by GaetanGrd** [comment]
Hey, please send your logs files 

## How to send your log file
> **1.** Launch BSManager and go to Settings.
> ⸻
> **2.** Scroll to the bottom of the page.
> ⸻
> **3.** Click on the `Open logs` button.
> ⸻
> **4.** Right-click on the log file to be sent and select `Copy`.
>    \- The requested file is usually the most recent log file, located at the bottom of the list.
> ⸻
> **5.** `Paste` your file in the channel where log files are requested.
![image](https://github.com/Zagrios/bs-manager/assets/40648115/ea966cf4-658b-48fe-a12c-ae0f32b31be9)

**Comment by Zagrios** [comment]
reopen if needed
