### ISSUE TITLE
[FEAT.] : Notification if some OneClicks are disabled

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#47]
Yeah I totaly forgot to implement that 😅

**Comment by GaetanGrd** [comment]
Bouuuuh

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Notification if some OneClicks are disabled](https://trello.com/c/Pmcufx9B/29-notification-if-some-oneclicks-are-disabled)
