### ISSUE TITLE
oculus token not working

### ISSUE THREAD

**Issue by minecrash1** [Zagrios/bs-manager#470]
when i enter my token in BS manager it's says "unable to download the manifest for this version; your login token may be invalid"

**Comment by Zagrios** [comment]
Hi, do you own the game on the Oculus Rift Store (PC) or on the Oculus Quest store (Standalone Headset) ?

**Comment by minecrash1** [comment]
> Hi, do you own the game on the Oculus Rift Store (PC) or on the Oculus Quest store (Standalone Headset) ?

I own it on the oculus quest store

**Comment by Zagrios** [comment]
Hi, make sure to have Beat Saber on your computer downloaded from the Oculus app before trying to download it with BSManager

**Comment by minecrash1** [comment]
I have my account with beat saber connected with the Oculus app on computer
but i don't see the game in my library in the app i don't know why

**Comment by Zagrios** [comment]
You have to claim it from its Store page first to have it in your library
 https://www.meta.com/en-gb/experiences/pcvr/beat-saber/1304877726278670

**Comment by minecrash1** [comment]
Thanks ! It worked, you saved me.

**Comment by lolo895** [comment]
it say that my oculus token is wrong
