### ISSUE TITLE
[BUG] : Cant start songs

### ISSUE THREAD

**Issue by ryecoonsy** [Zagrios/bs-manager#473]
## Bug Description

I am unable to start any of the songs I downloaded when I launch BSmanager. Even songs that came with the game. 
## Expected Behavior

I expected the songs to play when I pressed play.
## Screenshots

![image](https://github.com/Zagrios/bs-manager/assets/131566195/9a2f8ee5-82fb-4e7d-9e33-6cfcaf97ecd8)
![image](https://github.com/Zagrios/bs-manager/assets/131566195/28cff2e2-67b2-4151-8844-91e94161f3a6)
![image](https://github.com/Zagrios/bs-manager/assets/131566195/d0e2313d-0fda-4d47-8d88-40b42e9cdd7b)
![image](https://github.com/Zagrios/bs-manager/assets/131566195/786587a2-6ea6-4446-8673-724a54d67230)
![image](https://github.com/Zagrios/bs-manager/assets/131566195/90931da9-c797-4d4c-9638-d9f132bc2c97)
![image](https://github.com/Zagrios/bs-manager/assets/131566195/f457d800-d57f-4a55-8091-fa3ca1bc8fb7)

**Comment by Zagrios** [comment]
hey this problem is not related to BSManager, try asking on the BSMG discord server in the #pc-help channel
https://discord.gg/beatsabermods
