### ISSUE TITLE
[BUG] : BS manager taking forever to download a version of beat saber

### ISSUE THREAD

**Issue by GratisCrimson** [Zagrios/bs-manager#474]
## Bug Description
i have a bug where it is taking absurdely long to download a single version of beatsaber and it feels like it isnt even downloading anything.

## Additional context
it also says pls wait for the operation to finish running when i click on certain things

**Comment by Zagrios** [comment]
Hi, this issue can happen if you've entered your Steam Guard code wrongly
Are you still facing the issue ?

**Comment by GratisCrimson** [comment]
ive done it with the same code since, i then tried a new code and that didnt work either.

**Comment by Zagrios** [comment]
If you have a VPN, disable it.
If possible, try switching your internet connection (e.g., use a hotspot with your phone). We have had cases where the issue was resolved after switching the internet connection, even when switching back to the original one (weird but real😅)

**Comment by Zagrios** [comment]
reopen if needed
