### ISSUE TITLE
[BUG] : BSManager uses junctions instead of sumbolic links - therefore breaking funcitonality 

### ISSUE THREAD

**Issue by Fatalution** [Zagrios/bs-manager#475]
## Bug Description
I have all the maps / UserData / other stuff backed up in the cloud (OneDrive) folder. All the stuff that BSManager handles is stored in SharedContent folder and mirrors the BSManager setup. SharedContent folder is then symlink'd into the BSManager folder. 

However, when "linking" stuff from BSManager, all the created links are faulty. The reason is simple: BSManager created a **junction**, NOT a link, pointing to a folder that exists in the symbolic link - and this is **_bad_**. 

BSManager **_should_** use symbolic links instead

## Reproduction Steps

1. Copy SharedContent folder somewhere on your drive.
2. Rename the SharedContent folder in BSManager's folder.
3. Create the symbolic link from the SharedContent folder to BSManager folder.
4. Go to BSManager and download any Beat Saber version.
5. Try to link maps.
6. No maps load in BSManager.
7. Go to BeatSaber_Data/CustomLevels folder.
8. Click on it.
9. See error.

## Expected Behavior
There should be no error and linking should work as expected. 

## Additional info
Here is the diagram of what I'm trying to do (and failing)
![Снимок экрана 2024-05-07 120837](https://github.com/Zagrios/bs-manager/assets/17583199/325da414-6d9b-447f-b376-2335662c0152)

Recreating all the links myself works perfectly (but takes time)

**Comment by Zagrios** [comment]
Hi, the reason we use junctions instead of symbolic links is because Beat Saber does not follow symbolic links when reading files.
However, if you manage to get Beat Saber to work using symbolic links, I'm curious about how you created them 👀

**Comment by Fatalution** [comment]
> Hi, the reason we use junctions instead of symbolic links is because Beat Saber does not follow symbolic links when reading files.
> 
> However, if you manage to get Beat Saber to work using symbolic links, I'm curious about how you created them 👀 

This is not true. All my shared folders are symlinks (NOT junctions), and Beat Saber never had any problems reading them.

Again, the problem lies in BSManager itself. I DM'D you on Discord to provide more info

**Comment by Zagrios** [comment]
I've added an advanced option to use Symlinks instead of junctions in the [v1.5.0-alpha.4](https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.4)
