### ISSUE TITLE
[BUG] oculus token not working

### ISSUE THREAD

**Issue by meatman20** [Zagrios/bs-manager#479]
i am tryng to dowland version 1.18.0 i put the ocuilus token in but it says 
![Screenshot 2024-05-17 173551](https://github.com/Zagrios/bs-manager/assets/170114058/0e5ef3a6-b181-45d2-b9fe-6b948b9ab641)
 i have the game on steam i play onm quest 3

**Comment by Zagrios** [comment]
Hi, if you bought Beat Saber on Steam, choose the Steam platform when you want to download it with BSManager

**Comment by Zagrios** [comment]
Np, have fun playing Beat Saber 😉
