### ISSUE TITLE
[BUG] : When I clone the version weird stuff happens

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#487]
## Bug Description
When attempting to clone a version in BSManager, if the version name is not changed but the color is modified, upon the next restart of BSM, the version that was intended to be cloned will have its icon color changed to the color intended for the new version.

## Reproduction Steps
- follow gif send in private message.

**Comment by Zagrios** [comment]
![gvRWDdN](https://github.com/user-attachments/assets/30a1de65-62b1-4ebb-84b6-2d4009306056)
