### ISSUE TITLE
[BUG] : Launch arguments not being added.

### ISSUE THREAD

**Issue by Mawntee** [Zagrios/bs-manager#494]
## Bug Description
Cross post from the Discord server:
- Adding in a launch argument under "Advanced launch" literally does nothing, even if the launch arg is also in Steam itself.
*(also wtf is `--no-yeet` ???)*

## Reproduction Steps
1. Add launch argument
2. Launch game
3. Notice launch argument is nowhere to be found

## Expected Behavior
- Launch argument is added

## Screenshots
(last screenshot is plugin outputting current launch commands to console)
![image](https://github.com/Zagrios/bs-manager/assets/51247415/c7355915-cc4a-4acd-bfc1-1be665a307ae)
![image](https://github.com/Zagrios/bs-manager/assets/51247415/535ae0b6-dc90-4b36-bfcb-ccc3e7121a33)
![image](https://github.com/Zagrios/bs-manager/assets/51247415/4601a026-239e-4e06-99e1-e19b1f7dd9c5)

## Additional context

-   OS: Windows 10
-   Version: 1.29.1
-   BSM Version: v1.4.7

- Line 156 of log shows launch arg randomly not being added
- I don't recall changing any settings or doing anything differently.
- A while back the launch args were not working, then after a few tries of closing/re-opening, it suddenly starting working.
[2024-6-10-v1.4.7.log](https://github.com/user-attachments/files/15780283/2024-6-10-v1.4.7.log)

**Comment by Zagrios** [comment]
@Mawntee `--no-yeet` is an argument used by BSIPA
You can find them here : https://github.com/nike4613/BeatSaber-IPA-Reloaded/blob/master/docs/articles/command-line.md
