### ISSUE TITLE
[BUG] :black window

### ISSUE THREAD

**Issue by araja32** [Zagrios/bs-manager#501]
## Bug Description
whenever I open 1.18.0 and open the mods tab it shows a black screen like even the close button disappears

## Reproduction Steps

1. Download the Version when the Billie DLC Cameout
2. Click on click on the version then mods
3. download some mods close the app then reopen it and go back to mods
4. wait then you see a black screen
-->

## Expected Behavior
black screen in window

## Screenshots
![image](https://github.com/Zagrios/bs-manager/assets/173559070/d3f52fbe-0ad1-441d-bbfa-5cd02a77b276)

## System Specs
NVIDIA GeForce GTX 1660 SUPER
Intel(R) Core(TM) i5- 10400F CPU
16 GB of RAM 

-   OS: Windows 10
-   Version 22H2 (OS Build 19045.4529)
-->

## Additional context
https://github.com/Zagrios/bs-manager/assets/173559070/c0b60442-9a6f-4824-bdd4-9f087f60c105

I installed mods with that version but when i try to open it again it does that

**Comment by Zagrios** [comment]
@araja32 can you send your logs here ? (settings -> scroll down -> "open logs")

**Comment by araja32** [comment]
[2024-6-22-v1.4.7.log](https://github.com/user-attachments/files/16045008/2024-6-22-v1.4.7.log)
[2024-6-23-v1.4.7.log](https://github.com/user-attachments/files/16045009/2024-6-23-v1.4.7.log)
[2024-6-24-v1.4.7.log](https://github.com/user-attachments/files/16045010/2024-6-24-v1.4.7.log)
[2024-6-30-v1.4.7.log](https://github.com/user-attachments/files/16045011/2024-6-30-v1.4.7.log)

**Comment by araja32** [comment]
its seems to be fixed so im going to close it
![Screenshot 2024-07-09 115114](https://github.com/Zagrios/bs-manager/assets/173559070/5477b4ea-57d0-4180-9a01-4f5893467dc4)
