### ISSUE TITLE
[FEAT.] : Alert if dotnet 6 is not installed

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#53]
DepotDownloader need dotnet 6 to work.
Before download a BS version, check if dotnet 6 is present, if not, show alert with button to redirect to the download page of dotnet

**Comment by GaetanGrd** [comment]
Think add DotNet 6 in installer ;)

**Comment by Zagrios** [comment]
No because if you already have dotnet installed, there is no point in putting it in the installer. Or also maybe we only want to use other features than the downgrade.
I'm just going to do like all the other apps. Redirected user to dotnet download page

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Alert if dotnet 6 is not installed](https://trello.com/c/yvbmeOmo/28-alert-if-dotnet-6-is-not-installed)
