### ISSUE TITLE
[BUG] : No maps found for tag "Dance"

### ISSUE THREAD

**Issue by kgabriel-dev** [Zagrios/bs-manager#536]
## Bug Description
When I try to add maps in BSManager and select the filter *Dance*, it cannot find any maps. The other filters seem to worked, but I've only tested some of them.

## Reproduction Steps
1) Select a version of Beat Saber (I've checked it on 1.36.2 and 1.37.1)
2) Go to the *Maps* tab
3) Click "Add"
4) Check **only** the blue *Dance* tag and apply the filter
5) It should show that no maps are found.

## Expected Behavior
The program should display maps with this tag. It works on http://bsaber.com

## Screenshots
![image](https://github.com/user-attachments/assets/b2f37be9-230f-4eec-b663-814fd9b0e7dd)

## System Specs
- OS: Windows 11
- BSManager: v1.5.0-alpha.2

## Additional context
None

**Comment by Zagrios** [comment]
@kgabriel-dev thanks for the report! The fix will be available in the next alpha 👌
