### ISSUE TITLE
Improving the German translation file

### ISSUE THREAD

**Issue by kgabriel-dev** [Zagrios/bs-manager#544]
Hey. I am trying to improve the German translations for this program as there are some **minor** errors. Just some things like words written with an uppercase letter at the beginning when it should be a lowercase one, and vice versa. Or some small inconsistencies, e.g. using "du" and "Sie" (both "you" in English). Before sending the updated file (as a Pull Request or just sending you the file), I wanted to check it in the program. Could you help me build the program or something?

**Comment by Zagrios** [comment]
@kgabriel-dev
- I highly recommend you to install [Volta](https://volta.sh/) it will take care of Node for you, or manually install Node LTS by hand
- Clone the repository
- Navigate to the project folder and run the command `npm i`
- Finally, run the command `npm start`

**Comment by Zagrios** [comment]
All the steps are written in the [Contributing](https://github.com/Zagrios/bs-manager/blob/master/CONTRIBUTING.md) guide

Dont hesitate to reopen if needed
