### ISSUE TITLE
[BUG] : No Internet connection in Version 1.37.0

### ISSUE THREAD

**Issue by DawidDe** [Zagrios/bs-manager#545]
## Bug Description
When I install version 1.37.0 trough oculus account i get no internet in the game. my pc has internet. but leaderboards etc. are not working. On other versions it works.

## Reproduction Steps
Install BeatSaber V. 1.37.0 trough bs manager.
Then launch the Game and check internet connection

## Expected Behavior
Should have internet connection

## System Specs
Gigabyte B550M DS3H
Ryzen 5 5600X
RX 6600
16 gb ddr ram
2tb nvme ssd kingston

-   OS: Windows 11 Pro
-   Version 1.37.0

**Comment by Zagrios** [comment]
Hi, This most likely not an issue with BSM, I suggest you to ask on BSMG discord in the #pc-help channel
https://discord.gg/beatsabermods
