### ISSUE TITLE
[BUG] : can not update the last version and found the steam version game

### ISSUE THREAD

**Issue by vansto** [Zagrios/bs-manager#548]
## Bug Description
can not update the last version and found the steam version game

## Reproduction Steps
installed the last version bsmanager and steam beatsaber

## Screenshots
![1](https://github.com/user-attachments/assets/acd02b99-a219-4751-8d6d-20cf26fbb58c)

## System Specs
windows10 21H2

**Comment by Zagrios** [comment]
@vansto From what I see, BSM is unable to get the latest available versions of Beat Saber from GitHub.
Are you using a VPN? If yes, try disabling it. 
If it still doesn't work, try using a different internet connection (e.g., by sharing your phone's connection)

**Comment by vansto** [comment]
> @vansto From what I see, BSM is unable to get the latest available versions of Beat Saber from GitHub. Are you using a VPN? If yes, try disabling it. If it still doesn't work, try using a different internet connection (e.g., by sharing your phone's connection)

sorry my net too bad,i fixed after using google dns to resolve raw.githubusercontent.com
