### ISSUE TITLE
[BUG] : Screen Flickering

### ISSUE THREAD

**Issue by jddicaro** [Zagrios/bs-manager#592]
## Bug Description
During and after startup, several elements of the ui flicker. While this doesn't affect gameplay and usage, it's odd and kinda anoyying.

## Reproduction Steps
I am not sure how to reproduce this. After uninstalling and reinstalling, the issue stuck. This makes me think it might be an issue with my pc.

## Expected Behavior
I expected no flickering.

## Screenshots

https://github.com/user-attachments/assets/97df6f05-fbaa-4253-9474-b1b6a8cf6f6a

## System Specs
Windows 11
RTX 4060 (Y'know, it might be a driver issue...)
12th gen i5-12400F
V1.4.8

## Additional context
It kinda feels like beatsaber is affected? idk tho

**Comment by jddicaro** [comment]
i just did a video driver update and it got fixed lol

**Comment by jddicaro** [comment]
scratch that, it started again

**Comment by silentrald** [comment]
Hmmm, this seems to be a GPU problem for the Windows and Nvidia as described in issue 43122 in electronjs (Didn't link it so it won't be mentioned there). There mitigation was to disable the GPU acceleration on the app. This can be done in the pre-release version of BSM, try downloading the 1.5.0-alpha.4 release [here](https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.4). Then navigate to the settings page and scroll to the very far bottom and toggle off hardware acceleration.

![image](https://github.com/user-attachments/assets/417c5003-7f5c-4e08-b592-71185648d512)

The bug may not be handled by BSM, but I think you can bump up the issue in electronjs if you want to.

**Comment by jddicaro** [comment]
That fixed it! Thank you so much.
