### ISSUE TITLE
[BUG] : Mods don't download properly

### ISSUE THREAD

**Issue by TheRealLifeBasti** [Zagrios/bs-manager#606]
### Issue encountered

I wanted to report a problem. I tried to install new mods and noticed that they only download half and the download bar freezes. Similar problem with ArcViewer, the maps only download very slowly there. I've already tried changing my internet and reinstalling BS Manager but neither worked. I also tried resetting my PC, without success.

### Expected Behavior

The mods should always download smoothly and definitely

### Steps to Reproduce

![Screenshot 2024-10-10 181355](https://github.com/user-attachments/assets/4b798096-6f10-4cb0-841a-272201722d14)

This is what it looks like (its like this for half an hour)

### Operating System

Windows 11

### Version

latest

**Comment by Zagrios** [comment]
Hi thanks for the report !

Have you / Can you try with the latest Alpha of BSM ?

https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.4

**Comment by TheRealLifeBasti** [comment]
yes, its fixed. Thank youuuuuuu xDDDD
