### ISSUE TITLE
[FEAT.] : Schema v4 support for maps/songs

### ISSUE THREAD

**Issue by silentrald** [Zagrios/bs-manager#607]
### Problem

Currently, only v3 and below schemas are supported in BSM.

There is also an unhandled error when download maps/songs with schema v4 with BSM.

Try downloading **AJ Dispirito - BITE ME (V4)**

### Solution

Create an implementation to support v4 schema.

_**[If possible]** Add filtering or a broken UI icons on songs that are not supported by older versions of BS._
|Schema version|Min BS version|
|---:|---:|
|4.0.0|1.34.5|
|3.0.0| ? |
|2.1.0|1.31.0|
|2.0.0|1.0.0|

----

_**[Nice to have but not a requirement]** Support conversion between from each schema ie. v4 -> v2; v2 -> v4 etc._

### Alternative Solution

* Download a v3 version of the map
* Some kind of converter from v4 to v3

### Operating System

None

### Additional Context

References: https://bsmg.wiki/mapping/map-format/info.html

**Comment by Zagrios** [comment]
Thanks, I saw this issue a few days ago, but I didn't know where to find the new map format.
I will take advantage of the DepotDownloader issue to update that for v1.4 as well 👌

**Comment by silentrald** [comment]
> Thanks, I saw this issue a few days ago, but I didn't know where to find the new map format.
I will take advantage of the DepotDownloader issue to update that for v1.4 as well 👌

@Zagrios No probs. Can help with testing on this one.

---

Side note as well, might review the DepotDownloader binary as well if it should work on linux as well so that it won't be an issue in master.

**Comment by silentrald** [comment]
For reference: also applied in version 1.4.9 in commit 5e33efbb06132e28c8526f5cc7cc6cfd0c2ed97b
