### ISSUE TITLE
[BUG] : Cannot Login to Steam

### ISSUE THREAD

**Issue by swimwater** [Zagrios/bs-manager#612]
### Issue encountered

Using Windows 11 I tried to download a new version, but it timed out on the login window for steam. I saw a bug report [608](https://github.com/Zagrios/bs-manager/issues/608) describing the exact issue I was having so I moved to the alpha version. Still doesn't work.

Side Note: It will suddenly start working on occasion, as such I have two versions of beat saber installed already.

### Expected Behavior

1. Select new version
2. Login to steam
3. Version starts downloading

### Steps to Reproduce

1. Click on download (a new version)
2. Wait for login to load
3. Login doesn't load; error occurs

### Operating System

Windows 11

### Version

1.5.0-alpha.4

### Additional Context

[2024-10-14 18:46:05.485] [error] [
  [
    'Uncaught NonError: {"type":"Error","subType":"ConnectionTimeout","data":"Timeout connecting to Steam3."}',
    'file:///C:/Users/.../renderer/renderer.js',
    2,
    2021983,
    'Error: {"type":"Error","subType":"ConnectionTimeout","data":"Timeout connecting to Steam3."}'
  ]
]

**Comment by silentrald** [comment]
@swimwater the current alpha version `1.5.0-alpha.4` still doesn't contain the fix. The PR was only merged to master just this day/yesterday so this isn't released yet.

Although you can get the artifact build of this from actions which should be this one https://github.com/Zagrios/bs-manager/actions/runs/11326244900. Download the one that says `release-windows-latest`.
