### ISSUE TITLE
[BUG] : .json playlists are not detected

### ISSUE THREAD

**Issue by kek123321** [Zagrios/bs-manager#618]
### Issue encountered

BSManager doesn't recognize .json playlists

### Steps to Reproduce

[Rocker_Acc_v1.17.json](https://github.com/user-attachments/files/17404154/Rocker_Acc_v1.17.json)
[accsaber-rankedmaps-standard.json](https://github.com/user-attachments/files/17404156/accsaber-rankedmaps-standard.json)
[ChromiACC.json](https://github.com/user-attachments/files/17404158/ChromiACC.json)

### Operating System

Windows 11

### Version

1.5.0 alpha-4

**Comment by Zagrios** [comment]
Hi, thanks for reporting this 👌
Can I know where these playlists come from? (BeatLeader? ScoreSaber? other ?)

**Comment by kek123321** [comment]
accsaber-rankedmaps-standard.json comes from https://accsaber.com/maps theres download playlists button at the top
some other playlists i found in accsaber discord
