### ISSUE TITLE
[BUG] : Advanced launch unable to be deactivated

### ISSUE THREAD

**Issue by qqrz997** [Zagrios/bs-manager#620]
### Issue encountered

Advanced launch options always apply and, additionally, the button stays highlighted as if it were enabled. This is quite inconvenient for testing

https://github.com/user-attachments/assets/cc6b8fd4-1230-4176-b641-d14cbd026bd6

### Operating System

Windows 10

### Version

1.5.0-alpha.4

**Comment by Zagrios** [comment]
Yeah, advanced launch args are always used, regardless of whether the 'Advanced Launch' input is visible or not
The UX needs a bit of adjustment here 😅

**Comment by qqrz997** [comment]
they don't in the stable version. unless i misunderstand you, this is a bug and not a ux discrepancy. i should have clarified that but it is togglable normally

**Comment by Zagrios** [comment]
In the stable version, it works, yeah, but we've changed this behavior in the alpha version.
In changelogs:
`Advanced launch arguments are used even when the input field is closed`
(https://github.com/Zagrios/bs-manager/releases/tag/v1.5.0-alpha.4)

**Comment by qqrz997** [comment]
well i guess i was taking that 'bug' for granted. as a modding support and tester, that being toggleable was very useful for me. i could just disable all the args at once if i wanted to play as i normally would and remove the testing stuff.
