### ISSUE TITLE
[BUG] : Deeplinking not working in linux

### ISSUE THREAD

**Issue by silentrald** [Zagrios/bs-manager#627]
### Issue encountered

The `bsmanager://...` is not working correctly after building and running the `.AppImage`. This might be related to the `electron-builder` module.

### Expected Behavior

When accessing a link with the protocol of `bsmanager://...`, it should open the BSM application.

### Proposed Solution

Remove `AppImage` as a target build and replace it with `deb`, `rpm`, and `pacman`

|Build|Supported Distro|
|---|---|
|deb|Ubuntu, Debian|
|rpm|Fedora, OpenSUSE|
|pacman|Arch, Manjaro|

Also, this needs to be documented on the `docs/wiki` on how to run the installer builds.

### Operating System

Linux

### Version

1.5.0-alpha.4 (4a91fa04e75ddd0c00cee70a02faf049883abaad)

### Additional Context

Docs that maybe helpful:
* https://stackoverflow.com/a/66366790
* https://wiki.archlinux.org/title/Desktop_entries

Needed for OAuth PKCE to work correctly.

**Comment by Zagrios** [comment]
It works really well by packaging the app into a .deb` instead of an .appimage` :thinking:

Ingl, I'm tempted to release a `.deb` file instead of an `.appimage`. From what I've seen, with `.appimage` auto-updates will work, nor do custom protocols, because with `.appimage, the app isn’t really "installed" on the machine

**Comment by silentrald** [comment]
Yeah by the looks of it, an installer build such as `.deb` is better than an `.appimage`. Is there anything in the `package.json` file that you changed other than the target property?

Although I got deep linking to work with an `.appimage` build with a simple `.desktop` file. I just created a `bsmanager.desktop` within `~/.local/share/applications` then the ff content is:

```ini
#!/usr/bin/env xdg-open
[Desktop Entry]
Name=BSManager
Comment=Beat Saber Manager
GenericName=BSM
Exec=/home/path/to/BSManager-1.5.0-alpha.4.AppImage --no-sandbox "%U"
Icon=icon-path
Type=Application
StartupNotify=true
Categories=Utility;Game;
MimeType=x-scheme-handler/bsmanager;
```

But there is no automated way of doing this in `.appimage`.

So going the `deb` route build is probably are best bet. I'm going to check if it works in Arch as well.

**Comment by Zagrios** [comment]
Yeah you need to add that in package.json :
```json
"linux": {...},
"protocols": {
    "name": "BSManager",
    "schemes": {
        "bsmanager",
        "..."
    }
}
```

Maybe you can add the `protocols` inside the `linux` property, but i've not tested it

**Comment by silentrald** [comment]
Hmmm can't seem to install the `deb` on Arch. It's just telling me that I have uninstalled Ubuntu packages but I have them installed with arch which is weird. Trying building it in `rpm` since I think that has better support for Arch but the build process is failing on me. Will try to test this out further.

---
dpkg install in Arch
<pre>
 bs-manager depends on libgtk-3-0; however:
  Package libgtk-3-0 is not installed.
 bs-manager depends on libnotify4; however:
  Package libnotify4 is not installed.
 bs-manager depends on libnss3; however:
  Package libnss3 is not installed.
 bs-manager depends on libxss1; however:
  Package libxss1 is not installed.
 bs-manager depends on libxtst6; however:
  Package libxtst6 is not installed.
 bs-manager depends on xdg-utils; however:
  Package xdg-utils is not installed.
 bs-manager depends on libatspi2.0-0; however:
  Package libatspi2.0-0 is not installed.
 bs-manager depends on libuuid1; however:
  Package libuuid1 is not installed.
 bs-manager depends on libsecret-1-0; however:
  Package libsecret-1-0 is not installed.
</pre>

**Comment by Zagrios** [comment]
We can add something like that in package.json :
![image](https://github.com/user-attachments/assets/a54cd756-581f-4ac7-8056-b6db744538db)
Don't know if it will solve anything, but it's something to try

**Comment by silentrald** [comment]
Yeah that just adds more dependencies, but does not install the dependencies.

**Comment by silentrald** [comment]
Can you check on your end if it possible to build it in `rpm`?

**Comment by Zagrios** [comment]
I will check that when I'm home 👌

**Comment by silentrald** [comment]
Seems that the `pacman` build is working for Arch and can confirm the deeplink works there as well. Although still might wait on you on info about `rpm`.

Might need to document the builds so that users would know what to download.

`deb` - Ubuntu, Debian
`rpm` - Fedora, OpenSUSE
`pacman` - Arch, Manjaro

**Comment by Zagrios** [comment]
All of that should be supported
![image](https://github.com/user-attachments/assets/730c2af8-44e0-47da-a581-d93b65fe4402)

**Comment by silentrald** [comment]
Yep, listed those 3 builds since those distros are the more common ones. We can disregard the other linux builds for now and just wait for a feature request from future devs if they can give a rationale in using the other builds. What do you think?

**Comment by silentrald** [comment]
Might need to revert #577 since we can support an "installed" version rather than a portable version of BSM.
