### ISSUE TITLE
[BUG] : Auto-updater not working

### ISSUE THREAD

**Issue by spacky1** [Zagrios/bs-manager#631]
[2024-10-27-v1.4.9.log](https://github.com/user-attachments/files/17535278/2024-10-27-v1.4.9.log)

I've already updated to latest by manually downloading and running the installer but I thought you might want to take a look at this error

**Comment by Zagrios** [comment]
Yep, that issue can happen if you were still on the broken v1.4.9 release.
We deleted that release pretty quickly (within a few hours) and put up a new v1.4.9 that doesn’t mess with auto-update.
