### ISSUE TITLE
[FEAT.] : Add an option to unistall all mods at once

### ISSUE THREAD

**Issue by z3t4m4n** [Zagrios/bs-manager#637]
It is tiresome to uninstall one by one.

**Comment by Zagrios** [comment]
This is already available :wink:
![uninstall all mods](https://github.com/user-attachments/assets/30675c16-f6c8-4c0d-86ca-65b5f6422cb6)

**Comment by z3t4m4n** [comment]
Ooops, thanks and sorry for the noise.
