### ISSUE TITLE
[BUG] : Entire UI goes blank/black when downloading/looking at a song in the Maps Tab of a version

### ISSUE THREAD

**Issue by RedrcknRbn** [Zagrios/bs-manager#639]
When attempting to download/preview [https://beatsaver.com/maps/3fc06](https://beatsaver.com/maps/3fc06), the entire UI goes blank.

https://github.com/user-attachments/assets/d60771a0-3af5-4f6e-8e06-a61602246684

[2024-11-3-v1.4.10.log](https://github.com/user-attachments/files/17612547/2024-11-3-v1.4.10.log)

**Comment by Zagrios** [comment]
@RedrcknRbn Fixed in the v1.4.11
