### ISSUE TITLE
[BUG] : An error occurred while installing the playlist

### ISSUE THREAD

**Issue by cdytoby** [Zagrios/bs-manager#648]
### Issue encountered

The songs in my bookmark playlist in BeatSaver don't download with "One-Click" feature. A small window popup and immediately disappeared, then a windows notification shows up, says "An error occurred while installing the playlist".

problematic url: 
bsplaylist://playlist/https://api.beatsaver.com/playlists/id/436044/download/beatsaver-436044.bplist

Windows 11, Steam version of BeatSaber, and shared folder enabled for 2 different versions. 

BS-Manager version: v1.4.12

### Expected Behavior

Songs should be downloading after open the playlist one-click link

### Steps to Reproduce

1. Open this url: bsplaylist://playlist/https://api.beatsaver.com/playlists/id/436044/download/beatsaver-436044.bplist

### Operating System

Windows 11

### Version

1.4.12

### Additional Context

[2024-11-6-v1.4.12.log](https://github.com/user-attachments/files/17651721/2024-11-6-v1.4.12.log)

**Comment by cdytoby** [comment]
Additional information I forgot to mention:

I haven't played Beat Saber for quite a while. I used to use BeastSaber to bookmark and download songs using another software (which is a cmd line tool). Since I think earlier this year, I received a note from somewhere, that BeastSaber will no longer provide bookmark feature, and asked us to transfer it to BeatSaver. I did it back then, but One-Click feature in Mod-Assistant never worked back then. Then I give up. 

So the songs in this bookmark list are all imported from BeastSaber, not originally "marked" inside BeatSaver. I'm not sure if this is relevant.

**Comment by Zagrios** [comment]
@cdytoby  When I try to download the playlist manually (without BSM), I get a 'not found' error. I assume this is because your playlist is not public.
If that's the case, make it public, and it should work.

**Comment by cdytoby** [comment]
> @cdytoby When I try to download the playlist manually (without BSM), I get a 'not found' error. I assume this is because your playlist is not public. If that's the case, make it public, and it should work.

Can you tell me where can I find the button "make it public"?

![image](https://github.com/user-attachments/assets/41a715ce-911d-428b-9c22-b954c9fdea67)

![image](https://github.com/user-attachments/assets/19f0ba47-9024-4416-922d-3d1daead613c)

**Comment by Zagrios** [comment]
@cdytoby 
![image](https://github.com/user-attachments/assets/75ff0ce0-8034-4732-8407-4830b9c417e5)
![image](https://github.com/user-attachments/assets/5b30773b-4f6d-4588-bec1-1ec3f06500fd)

**Comment by cdytoby** [comment]
Oh, ok, it seems bookmark playlist is not public, and I can't make it public. 

Can I bookmark to my new public playlist instead of private playlist?

It's very very very inconvenient that I have to first bookmark, then download-reupload to another playlist, then one-click the new list.

This is a more discussion question rather then the software bug.

**Comment by cdytoby** [comment]
Or at least, can you make it work without one-click, I mean, just open the playlist file on local file system? right now if I open the playlist file, BSManager just open normally, and ignore the file I want it to open.

**Comment by Zagrios** [comment]
Are you sure you can't ? I'm seeing public bookmark playlists on the playlists page rn 🤔 
![image](https://github.com/user-attachments/assets/57ef261a-4153-429e-ac43-627788ae11ea)

**Comment by Zagrios** [comment]
> Or at least, can you make it work without one-click, I mean, just open the playlist file on local file system? right now if I open the playlist file, BSManager just open normally, and ignore the file I want it to open.

Its possible on the v1.5.0 of BSM, you can download the most up to date version of it from here (but its still in developpement stage):
[release-windows-latest](https://github.com/Zagrios/bs-manager/actions/runs/11705810779/artifacts/2152688372)

**Comment by cdytoby** [comment]
> Are you sure you can't ? I'm seeing public bookmark playlists on the playlists page rn 🤔 ![image](https://private-user-images.githubusercontent.com/40181755/383734805-57ef261a-4153-429e-ac43-627788ae11ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5Mjk1MDQsIm5iZiI6MTczMDkyOTIwNCwicGF0aCI6Ii80MDE4MTc1NS8zODM3MzQ4MDUtNTdlZjI2MWEtNDE1My00MjllLWFjNDMtNjI3Nzg4YWUxMWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDIxNDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTNlMjNkYmZmZDk4MWE1OWRiZjBmNmE5ZmEzY2U3YjFlYmQ2NDk0YTRkNzU4MTQ0YmNjZmRlYzRkNWFjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dS6t_XBCA2x1DqZ7IDwZMCOp63FN5X2umV5NTjAneQQ)

I can't. I don't have "Edit" button on the "Bookmarks". 

I created a new Playlist called "Bookmarks", but when I bookmark any song, it will add to the private one, not public one. It could be possible that this is due to  the problem that this bookmark is "imported", not created.

**Comment by cdytoby** [comment]
> > Or at least, can you make it work without one-click, I mean, just open the playlist file on local file system? right now if I open the playlist file, BSManager just open normally, and ignore the file I want it to open.
> 
> Its possible with the v1.5.0 of BSM, you can download the most up to date version of it from here (but its still in developpement stage): [release-windows-latest](https://github.com/Zagrios/bs-manager/actions/runs/11705810779/artifacts/2152688372)

I'll try it tomorrow, thanks for the info.

**Comment by cdytoby** [comment]
Update:

I tested 1.5.0 alpha4, and noticed that the feature, that reads bplist file and download the list, can only download the first "not downloaded" one in the list. Should I create a new bug for that?

I tested both one-click of public playlist, and a playlist file downloaded from my bookmark account.

Log here:
[2024-11-7-v1.5.0-alpha.4.log](https://github.com/user-attachments/files/17668947/2024-11-7-v1.5.0-alpha.4.log)

**Comment by Zagrios** [comment]
@cdytoby Ok, I’ve reproduced the error on my end, so I’ll use this issue to fix it 👌.
But I've been able to temporarily fix it by removing the `(1)` at the end of the filename; Rename your playlist file to remove the `(1)`, and it should work.

**Comment by cdytoby** [comment]
> @cdytoby Ok, I’ve reproduced the error on my end, so I’ll use this issue to fix it 👌. But I've been able to temporarily fix it by removing the `(1)` at the end of the filename; Rename your playlist file to remove the `(1)`, and it should work.

Thanks for confirming it, however remove the `(1)` doesn't help, same issue happens.

**Comment by cdytoby** [comment]
Hello, update:

recent update solves this original issue now. I can one-click download my bookmark list now. 

You can do whatever you want to this ticket.

**Comment by Zagrios** [comment]
🙌
