### ISSUE TITLE
[FEAT.] : add "remember my choice" when delete maps

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#66]
**Is your feature request related to a problem? Please describe.**
omg, it’s so boring this pop-up when I want to delete maps, isn’t it possible to add a check box to get rid of it?

![image](https://user-images.githubusercontent.com/40648115/210594008-c090cdb8-7ddc-4602-bf59-269d90457d2e.png)

**Comment by Zagrios** [comment]
omg do you know you can delete multiple maps in once ? but i understant i will add that

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [add "remember my choice" when delete maps](https://trello.com/c/i62HZuyK/26-add-remember-my-choice-when-delete-maps)
