### ISSUE TITLE
[BUG] : The oculus token has differ signature then FRLA

### ISSUE THREAD

**Issue by TheCPAKA** [Zagrios/bs-manager#668]
### Issue encountered

I wonna to downgrade BeatSaber version and i need an oculus token, app by default recognies only token started with FRLA... but https://developer.oculus.com/manage/ has another type of token, started with OCAF...

### Expected Behavior

App accepts mask for oculus token started with OCAF

### Operating System

None

### Version

1.4.12

![Untitled](https://github.com/user-attachments/assets/a30b4dd2-80f4-461d-995c-64e1bb4df34d)

**Comment by boomer69420** [comment]
https://github.com/Zagrios/bs-manager/wiki/How-to-obtain-your-Oculus-Token
Use this guide, but instead of going to "Headers," go to "Payload," and your code starting with FRL is there.

**Comment by TheCPAKA** [comment]
@boomer69420 Thanks, i looked into wrong place
