### ISSUE TITLE
[Question] : Mods installed in /IPS/Plugins instead of /Plugins/?

### ISSUE THREAD

**Issue by ElaineGilstrom** [Zagrios/bs-manager#678]
Hi, I'm mostly posting this because I thought BSManager wasn't running correctly on my computer as I was clicking install mods then the mods weren't showing up in my plugins folder so I had thought "Mods are not being installed by bs manager" when in reality they were just going to a folder I didn't know existed. So, my question is: Why install mods into /IPA/Plugins/ instead of the /Plugins/ folder in the root directory of the beat saber folder when the IPA folder is less transparent to the end user, and mod manager has already set the precedent of using the root plugins folder?

**Comment by AltyFox** [comment]
This is how mods are supposed get installed.  IPA moves them when it's run for this first time.  Something is going wrong with your install, post your log file

**Comment by ElaineGilstrom** [comment]
I figured out what was going on. Somehow the driver for my CV1 got corrupted and that was causing a whole bunch of stuff to go wrong down stream

**Comment by ElaineGilstrom** [comment]
Unless you'd like me to delete this, I'll just close this so people can find this later.
