### ISSUE TITLE
[BUG] : steam instance not showing mod menu ingame

### ISSUE THREAD

**Issue by hashashafashasha** [Zagrios/bs-manager#680]
### Issue encountered

the mod menu that usually appears to the left of the menu while ingame is absent while in a steam instance. it works perfectly fine in the other instance I have of the same version, but specifically the instance using the steam logo has this issue
I can tell that my installed mods are working since the AdBlocker mod is working, which is visible from the main menu, but nothing else works

### Operating System

None

**Comment by Zagrios** [comment]
Fixed

![image](https://github.com/user-attachments/assets/ce9eaa25-d019-44d7-841c-ba6d585fc136)
