### ISSUE TITLE
[BUG] : i cant add another version to beat saber

### ISSUE THREAD

**Issue by duckyyy52** [Zagrios/bs-manager#689]
### Issue encountered

every time i try to add another version it says unknown error

### Operating System

Windows 11

### Version

1.4.14

**Comment by silentrald** [comment]
Can you post your logs?
![image](https://github.com/user-attachments/assets/eb21c6af-2e45-43dd-899a-15a67594716b)

**Comment by duckyyy52** [comment]
C:\Users\kianp\AppData\Roaming\bs-manager\logs

**Comment by duckyyy52** [comment]
![image_2024-12-22_175413801](https://github.com/user-attachments/assets/0b542ec4-fc11-4183-b704-6a26d00d4a9c)

**Comment by silentrald** [comment]
@duckyyy52 

> ![image_2024-12-22_175413801](https://github.com/user-attachments/assets/0b542ec4-fc11-4183-b704-6a26d00d4a9c)

Yep, drop the latest log file here (in this case 2024-12-22), so we can check the error in logs.

**Comment by duckyyy52** [comment]
[2024-12-22-v1.4.14.log](https://github.com/user-attachments/files/18223538/2024-12-22-v1.4.14.log)

**Comment by silentrald** [comment]
@duckyyy52 

BSManager couldn't create this folder `C:\Users\<you>\BSManager` because of permission issues. Just run BSManager in admin mode and this should resolve the issue.

**Comment by duckyyy52** [comment]
how do i do that?

**Comment by duckyyy52** [comment]
it didnt work

**Comment by silentrald** [comment]
@duckyyy52 

Can you resend your logs again? Will check if there is any changes with the errors.

**Comment by duckyyy52** [comment]
[2024-12-22-v1.4.14.log](https://github.com/user-attachments/files/18223659/2024-12-22-v1.4.14.log)

**Comment by duckyyy52** [comment]
i got it working, thanks

**Comment by silentrald** [comment]
@duckyyy52 
No probs, just close the issue if there are no more concerns.

**Comment by duckyyy52** [comment]
will do
