### ISSUE TITLE
[BUG] : NPM missing as requirement in the AUR package

### ISSUE THREAD

**Issue by owohappy** [Zagrios/bs-manager#701]
### Issue encountered

NPM is missing as a dependency in the AUR package

### Operating System

Linux

**Comment by silentrald** [comment]
@owohappy will be added later today.

**Comment by Insprill** [comment]
I'm the AUR packager; this has been resolved. In the future, please leave issues with AUR packages on the page for that package. Maintainers often don't look at every issue for the source repo, so commenting there will get your issue resolved faster.
