### ISSUE TITLE
[BUG] : BSIPA Installation Failed

### ISSUE THREAD

**Issue by Reynbow** [Zagrios/bs-manager#711]
### Issue encountered

No matter what mod I try to install I get this error.

![image](https://github.com/user-attachments/assets/c4f24260-5199-4cc2-b104-7ca2cad93b41)

### Steps to Reproduce

Install any mod.

### Operating System

None

### Additional Context

I have installed the recommended version of Beat Saber 1.39.1 as recommended on the home page.
Not sure where to go with this.

**Comment by Reynbow** [comment]
Log file here

[2024-12-23-v1.4.14.log](https://github.com/user-attachments/files/18227299/2024-12-23-v1.4.14.log)

**Comment by Reynbow** [comment]
I have confirmed that the folder where the Beat Saber instance is being patched to or downloaded to does exist
![image](https://github.com/user-attachments/assets/1a1300ba-eb13-4add-9332-2632cffb1227)

I have tried running BSManager with admin rights.

Running IPA.exe under normal permissions seems to also show this error:
![image](https://github.com/user-attachments/assets/69c93543-e64e-4ea0-b4ac-5c4a72e0a211)

But running it as admin does not:
![image](https://github.com/user-attachments/assets/9e154281-e702-40bd-91b4-1e2bf4636b13)

**Comment by silentrald** [comment]
@Reynbow

Do you have Windhawk installed? if you do, try to disable or remove it when installing mods since it interferes with that file in particular.

**Comment by Reynbow** [comment]
Hot damn. That's such an odd interaction. I did have it installed, just uninstalled since I don't really use it. Now it's working. Thanks!

**Comment by Claydude33** [comment]
Im having the same problem on my pc and I don't have windhawk
