### ISSUE TITLE
[BUG] : Error "Unable to obtain the manifest required for download." when trying to install version. (ANY VERSION)

### ISSUE THREAD

**Issue by Frakonsoll** [Zagrios/bs-manager#714]
[2024-12-26-v1.4.14.log](https://github.com/user-attachments/files/18253696/2024-12-26-v1.4.14.log)
### Issue encountered

Hey! I am trying to download version 1.37.0 using platform Oculus Store. I entered token without errors, i even tried to put it manually, but unfortunately, it doesnt work. Also i tried different versions, but it didnt also doesnt work. Someone help me?
![image](https://github.com/user-attachments/assets/d95cd1e4-e602-4a35-8225-d17c59dbe0ef)

### Operating System

Windows 11

### Version

1.4.14

### Additional Context

Log
[2024-12-26-v1.4.14.log](https://github.com/user-attachments/files/18253696/2024-12-26-v1.4.14.log)

**Comment by AltyFox** [comment]
Log out of the Oculus app on your PC, and log back in. Then obtain a new token.

**Comment by Frakonsoll** [comment]
> Log out of the Oculus app on your PC, and log back in. Then obtain a new token.

Still. I think something with BSManager's files. I have new and clear app.
![image](https://github.com/user-attachments/assets/58a675e9-1a12-4aa8-ae40-5433994cde14)

**Comment by AltyFox** [comment]
Join our Discord and make a support thread.  It'll be easier to help

**Comment by Frakonsoll** [comment]
okay

**Comment by Zagrios** [comment]
(His game was a pirated copy)
