### ISSUE TITLE
[FEAT.] : Drag drop map to install it

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#75]
**Is your feature request related to a problem? Please describe.**
We can't manually install maps on a version.

**Describe the solution you'd like**
Drag and drop folder or zip of a map onto the liste of maps to install it

**Describe alternatives you've considered**
No alternative

**Additional context**

![drag drop map](https://user-images.githubusercontent.com/40181755/210887304-47ab6c4c-3506-46d7-87e7-2d046acddd6b.gif)

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Drag drop map to install it](https://trello.com/c/KnCrFEP8/13-drag-drop-map-to-install-it)
