### ISSUE TITLE
[FEAT.] : Drag drop mod to install it

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#76]
**Is your feature request related to a problem? Please describe.**
We can't manually install mod to a version.

**Describe the solution you'd like**
Drag and drop zip or dll of a mod onto the liste of mods to install it

**Describe alternatives you've considered**
No alternative

**Additional context**

![drag drop mod](https://user-images.githubusercontent.com/40181755/210889138-6f8c8d63-952d-46f0-93eb-6a0d7963b9e9.gif)

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Drag drop mod to install it](https://trello.com/c/Ov8lyv8K/12-drag-drop-mod-to-install-it)
