### ISSUE TITLE
[BUG] can't uninstall any version

### ISSUE THREAD

**Issue by GaetanGrd** [Zagrios/bs-manager#8]
**Describe the bug**

**To Reproduce**
1. Launch Bs Manager
2. Dowload any version
3. uninstall that version

**Screenshots**
![OneEcran](https://user-images.githubusercontent.com/40648115/194007620-b7ce73c9-988b-43ab-8618-14e0cdf6b91c.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version : 0.1.0

**Comment by Zagrios** [comment]
If you restart BSManager, the installed version still appears?

**Comment by GaetanGrd** [comment]
Hi, after multiple test, this bug appears only on my work laptop.

**Comment by GaetanGrd** [comment]
Problem solved after install steam
