### ISSUE TITLE
[FEAT.] : replace patreon button by mee6 donation system

### ISSUE THREAD

**Issue by Zagrios** [Zagrios/bs-manager#83]
**Is your feature request related to a problem? Please describe.**
We do not use patreon anymore, we use mee6 donation.

Redirect the use to this page : https://mee6.gg/m/bsmanager

**Comment by GaetanGrd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [replace patreon button by mee6 donation system](https://trello.com/c/aYIEppd9/23-replace-patreon-button-by-mee6-donation-system)
